import google.generativeai as genai
import os
import json
import glob
from dotenv import load_dotenv
from datetime import datetime

# Load API Key
load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("❌ ERROR: Key not found in .env")

genai.configure(api_key=api_key)

# 1. Configuration setup
generation_config = {
    "temperature": 0.4,
    "top_p": 0.95,
    "top_k": 64,
    "max_output_tokens": 8192,
}

# 2. Model definition (Switched to 1.5 as 2.5 is not yet available)
MODEL_NAME = "models/gemini-1.5-flash" 

print(f"🤖 Using model: {MODEL_NAME}")

# 3. Initialize Model with English Persona
model = genai.GenerativeModel(
    model_name=MODEL_NAME,
    generation_config=generation_config, 
    system_instruction="""
    You are a Senior Geopolitics Analyst and Intelligence Specialist.
    Your mission is to read raw news from various sources and produce a high-quality executive report (Daily Briefing). 
    Do not use '#' or '*' in the final text.
    
    ANALYSIS GUIDELINES:
    1. NOISE FILTER: Ignore gossip, sports, or irrelevant local crimes.
    2. FOCUS: Prioritize armed conflicts, military movements, economic bloc decisions (BRICS, EU, NATO), and humanitarian crises.
    3. SYNTHESIS: Cross-reference information. If Reuters and Telegram mention the same event, combine the data.
    4. IMPARTIALITY: Maintain a neutral, technical, and direct tone.
    """
)

def load_latest_json_files():
    """Fetches latest JSON files generated by scrapers."""
    # Sort files by modification time
    news_files = sorted(glob.glob("global_news_dump_*.json"), key=os.path.getmtime)
    telegram_files = sorted(glob.glob("telegram_dump_*.json"), key=os.path.getmtime)
    
    data_content = []

    if news_files:
        latest_news = news_files[-1]
        print(f"📂 Loading Web News: {latest_news}")
        with open(latest_news, 'r', encoding='utf-8') as f:
            data_content.extend(json.load(f))
    
    if telegram_files:
        latest_telegram = telegram_files[-1]
        print(f"📂 Loading Telegram: {latest_telegram}")
        with open(latest_telegram, 'r', encoding='utf-8') as f:
            data_content.extend(json.load(f))
            
    return data_content

def generate_daily_briefing(direct_data=None):
    print("🧠 Starting Intelligence Analysis with Gemini...")
    
    # 1. Determine data source (Memory vs. Disk)
    if direct_data:
        raw_data = direct_data
        print(f"📂 Using {len(raw_data)} items from memory.")
    else:
        raw_data = load_latest_json_files()
    
    # 2. Stop if no data
    if not raw_data:
        print("⚠️ No data found to analyze.")
        return None

    # 3. Convert List to String for the prompt
    try:
        data_str = json.dumps(raw_data, ensure_ascii=False, indent=2)
    except Exception as e:
        print(f"❌ Error converting data to string: {e}")
        return None

    # 4. Construct the Prompt (Instructions in English, Output requested in PT-BR)
    user_prompt = f"""
    Here is the raw data collected today ({datetime.now().strftime('%d/%m/%Y')}):
    
    {data_str}
    
    ---
    TASK:
    Write a Daily Executive Summary.
    
    DESIRED STRUCTURE:
     🌍 GLOBAL INTELLIGENCE REPORT - {datetime.now().strftime('%d/%m/%Y')}
    
     🔥 Critical Highlights (High impact headlines)
     [Topic 1]: 2-line summary.
    
     ⚔️ Conflicts and Security (Defense, War, Terrorism)
    (Group news by region or conflict)
    
     💰 Geoeconomics and Diplomacy
    (Agreements, sanctions, economic blocs)
    
     👁️ OSINT radar (Telegram info/Unofficial sources)
    
     🔗 Sources
    """

    print("⏳ Sending data to Gemini (this may take a few seconds)...")
    
    try:
        response = model.generate_content(user_prompt)
        report_text = response.text
        
        # Save report
        filename = f"FINAL_REPORT_{datetime.now().strftime('%Y-%m-%d')}.md"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(report_text)
            
        print(f"\n✅ Report generated successfully: {filename}")
        # print(report_text) # Uncomment to view in terminal
        return report_text

    except Exception as e:
        print(f"❌ AI Generation Error: {e}")
        return None